version: '3'
services:
  spire-server:
    build: ./docker/spire-server
    hostname: spire-server
    tty: true
    privileged: true
    ports:
      - "9081:9081"
  echo:
    build: ./docker/echo
    hostname: echo
    tty: true
    privileged: true
    links:
      - spire-server
    ports:
      - "8081:8081"
  echo-agent:
    build: ./docker/echo-agent
    hostname: echo-agent
    tty: true
    privileged: true
    links:
      - spire-server
    volumes:
      - spire-socket:/tmp
  echo-envoy:
    build: ./docker/echo-envoy
    hostname: echo-envoy
    tty: true
    privileged: true
    links:
      - spire-server
    volumes:
      - spire-socket:/tmp

  web:
    build: ./docker/web
    hostname: web
    tty: true
    privileged: true
    links:
      - spire-server
      - echo
    ports:
      - "8080:8080"

volumes:
  spire-socket: